In [2]:
import torch
import numpy as np

## Tensors
pytorch adalah library yang memproses tensor. tensor adalah variabel berupa angka, vektor, matrix, atau dimensional array
tensor banyak dipakai di machine learning

In [2]:
#number
t1 = torch.tensor(4.)
t1

tensor(4.)

4. berarti 4.0
hal ini menunjukkan angka tersebut adalah floating number

In [3]:
t1.dtype

torch.float32

In [6]:
#vektor
t2 = torch.tensor([4, 3., 2, 1])
t2

tensor([4., 3., 2., 1.])

In [9]:
#matriks
t3 = torch.tensor([[1.,2],
                   [3,4],
                   [5,6.]])
t3

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [17]:
# 3d array
t4 = torch.tensor([[[11,12.,13],[13,14,15]],[[15,16,17],[17,18,19]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [12]:
# ga termasuk vektor, karena cuman variabel biasa
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [13]:
print(t2)
t2.shape

tensor([4., 3., 2., 1.])


torch.Size([4])

In [15]:
print(t3)
t3.shape

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


torch.Size([3, 2])

In [18]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

In [19]:
# Matrix
t5 = torch.tensor([[5., 6, 11], 
                   [7, 8], 
                   [9, 10]])
t5

ValueError: expected sequence of length 3 at dim 1 (got 2)

inget, tensor bukan list array kayak numpy
jadi bentuk dimensi yangga sesuai bakal error

## operasi tensor dan gradient

In [20]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

parameter requires_grad berfungsi agar pytorch dapat otomatis menghitung derivative (turunan) dari variabel tersebut

In [47]:
# fungsi aritmatika
y = w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [48]:
# hitung turunan, cuman bisa sekali
y.backward()

In [37]:
# tampilkan gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


x gapunya gradient, soalnya ga pakai requires grad true

## tensor dan Numpy

In [3]:
x = np.array([[1,2],[3,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [4]:
#torch ke numpy, pakai memori yang sama dengan x
y = torch.from_numpy(x)
y

# bisa begini juga, tapi ini bakal makan memori baru (copy data baru)
y = torch.tensor(x)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

numpy dan tensor keliatannya sama aja
tapi tensor bakal dikerjain oleh GPU biar lebih cepet

In [5]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [6]:
# konversi torch tensor ke numpy
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

ada namanya CUDA, buat ngejalanin kode python pakai GPU
kalau pakai pytorch, bisa manfaatin CUDA ini
intinya pytorch buat jalanin program pakai GPU, biar komputasi makin cepet